An exception occured in <%= @processor -%>!

<%= @message -%>

<%= @error.class.name -%>: <%= @error.message -%>

<%= @error.backtrace.join("\n\t") -%>
